version: "3"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: build/go/Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./:/code
    tty: true
    links:
      - mysql
  mysql:
    container_name: mysql
    build: build/mysql
    ports:
      - 3305:3305
    volumes:
      - ./database/mysql:/var/lib/mysql
      - ./database/my.conf:/etc/mysql/my.conf
      - ./database/init/:/docker-entrypoint-initdb.d
    env_file:
      - build/mysql/.env
    command: mysqld --port 3305 --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    hostname: mysql